language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y libspatialindex-dev libgeos-dev gdal-bin

install:
  - pip install -r dev-requirements.txt

script:
  - python -m pytest tests
